Job approval command

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,6 +35,38 @@ job_environments:
     WP_DB_NAME: planet4-testpand_wordpress_develop
     WP_STATELESS_BUCKET: planet4-test-pandora-stateless-develop
 
+commands:
+  approve_job:
+    description: "Approve an on-hold job."
+    parameters:
+      job_name:
+        type: string
+    steps:
+      - run:
+          name: Unhold job.
+          command: |
+            $workflow_id=$(cat /tmp/workspace/approve_workflow)
+
+            url="https://circleci.com/api/v2/workflow/$WORKFLOW_ID/job"
+
+            # Get workflow details
+            workflow=$(curl -s -u "${CIRCLE_TOKEN}": -X GET --header "Content-Type: application/json" "$url")
+            # Get approval job id
+            job_id=$(echo "$workflow" | jq -r '.items[] | select(.name=="<< parameters.job_name >>") | .approval_request_id ')
+
+            if [[ -z $job_id ]]; then
+              echo "Approval ID not found"
+              exit 1
+            fi
+
+            echo "Approving << parameters.job_name >> for workflow $url"
+            echo "Job ID: ${job_id}"
+            curl \
+              --header "Content-Type: application/json" \
+              -u "${CIRCLE_TOKEN}:" \
+              -X POST \
+              "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/approve/${job_id}"
+
 job_definitions:
   visualtests_reference_steps: &visualtests_reference_steps
     docker:
@@ -156,30 +188,31 @@ job_definitions:
         type: boolean
         default: false
     steps:
+      - checkout:
+          path: /home/circleci/checkout
       - attach_workspace:
           at: /tmp/workspace
       - run: activate-gcloud-account.sh
       - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make deploy
+      - run:
+          name: Extract workflow from commit message
+          command: |
+            GIT_COMMIT_MSG=$(git --git-dir=/tmp/workspace/src/.git log --format=%B -n 1 "$CIRCLE_SHA1")
+            UNHOLD_WORKFLOW_LINE=$(echo $GIT_COMMIT_MSG | grep '^\/unhold ' | cut -d )
+            if [[ -z $UNHOLD_WORKFLOW_LINE ]]; then
+              echo "Nothing to unhold"
+              exit 0;
+            fi
+            WORKFLOW_ID=${UNHOLD_WORKFLOW_LINE#"/unhold "}
+            echo $WORKFLOW_ID > /tmp/workspace/approve_workflow
+      - approve_job:
+          job_name: instance-ready
       - when:
           condition: << parameters.is_prod >>
           steps:
-            - run:
-                name: Initiate finish-staging (approve rollback but it won't really)
-                command: |
-                  url="https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job"
-
-                  # Get workflow details
-                  workflow=$(curl -s -u "${CIRCLE_TOKEN}": -X GET --header "Content-Type: application/json" "$url")
-                  # Get approval job id
-                  job_id=$(echo "$workflow" | jq -r '.items[] | select(.name=="rollback-staging") | .approval_request_id ')
-
-                  echo "Finishing staging."
-                  echo "Job ID: ${job_id}"
-                  curl \
-                    --header "Content-Type: application/json" \
-                    -u "${CIRCLE_TOKEN}:" \
-                    -X POST \
-                    "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/approve/${job_id}"
+            - run: echo $CIRCLE_WORKFLOW_ID > /tmp/workspace/approve_workflow
+            - approve_job:
+                job_name: rollback-staging
       - when:
           condition: << parameters.notify >>
           steps:
